from challenge_3 import brute_force_xor
from challenge_5 import encrypt

class CPValueError(Exception):
    pass
